AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3 Miro Banner Accepters

Resources:
  # HTTP API
  MiroBannerAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      # CORS configuration - this is open for development only and should be restricted in prod.
      # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-httpapi-httpapicorsconfiguration.html   
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"   
        AllowOrigins: 
          - "*"      

  ## Lambda functions
  MiroBannerAcceptersRequestFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: getSignedURL/
      Handler: app.handler
      Runtime: nodejs16.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          MiroBannerAccepters: !Ref S3MiroBannerAcceptersBocketUsersSubfolder
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3MiroBannerAccepters
        ## This permission allows the Lambda function to request signed URLs
        ## for objects that will be publicly readable. Uncomment if you want this ACL.
        - Statement:
          - Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${S3MiroBannerAccepters}/'
            Action:
              - s3:putObjectAcl
      Events:
        UploadAssetAPI:
          Type: HttpApi
          Properties:
            Path: /uploads
            Method: get
            ApiId: !Ref MiroBannerAPI  

  ## S3 bucket
  S3MiroBannerAccepters:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
            - "*"
          AllowedMethods:
            - GET
            - PUT
            - HEAD
          AllowedOrigins:
            - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  
  ## S3 Bucket "Users" subfolder (this is where the User IDs of the users who accepted the terms banner will be stored)
  S3MiroBannerAcceptersBocketUsersSubfolder:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3MiroBannerAccepters}/users'

  ## S3 Bucket "Web Assets" subfolder (this is where you can host the "app.html" and "modal.html" files)
  S3MiroBannerAcceptersBocketWebAssetsSubfolder:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3MiroBannerAccepters}/webassets'

  ## S3 Bucket policy (This permission will make the contents of the S3 bucket publicly readable)
  ProductBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3MiroBannerAccepters
      PolicyDocument:
        Id: PublicReadPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub 'arn:aws:s3:::${S3MiroBannerAccepters}/*'
          Condition: {}

## Take a note of the outputs for deploying the workflow templates in this sample application
Outputs:
  APIendpoint:
    Description: 'HTTP API endpoint URL'
    Value: !Sub 'https://${MiroBannerAPI}.execute-api.${AWS::Region}.amazonaws.com'
  S3MiroBannerAcceptersBucket:
    Description: 'S3 bucket that captures users who have accepted the T&C banner in Miro'
    Value: !Ref 'S3MiroBannerAccepters'
